import fs from 'fs';
import path from 'path';

const b1 = [
{ id: 1, quote: "على قدر أهل العزم تأتي العزائم", author: "المتنبي", category: "طموح" },
{ id: 2, quote: "وتأتي على قدر الكرام المكارم", author: "المتنبي", category: "أخلاق" },
{ id: 3, quote: "إذا غامرت في شرف مروم فلا تقنع بما دون النجوم", author: "المتنبي", category: "طموح" },
{ id: 4, quote: "فطعم الموت في أمر صغير كطعم الموت في أمر عظيم", author: "المتنبي", category: "شجاعة" },
{ id: 5, quote: "الرأي قبل شجاعة الشجعان هو أول وهي المحل الثاني", author: "المتنبي", category: "حكمة" },
{ id: 6, quote: "فإذا هما اجتمعا لنفس حرة بلغت من العلياء كل مكان", author: "المتنبي", category: "حكمة" },
{ id: 7, quote: "الخيل والليل والبيداء تعرفني والسيف والرمح والقرطاس والقلم", author: "المتنبي", category: "اعتزاز" },
{ id: 8, quote: "أنا الذي نظر الأعمى إلى أدبي وأسمعت كلماتي من به صمم", author: "المتنبي", category: "أدب" },
{ id: 9, quote: "إذا رأيت نيوب الليث بارزة فلا تظنن أن الليث يبتسم", author: "المتنبي", category: "حكمة" },
{ id: 10, quote: "ما كل ما يتمنى المرء يدركه", author: "المتنبي", category: "حكمة" },
{ id: 11, quote: "تجري الرياح بما لا تشتهي السفن", author: "المتنبي", category: "حكمة" },
{ id: 12, quote: "ومن يهن يسهل الهوان عليه ما لجرح بميت إيلام", author: "المتنبي", category: "كرامة" },
{ id: 13, quote: "لا يسلم الشرف الرفيع من الأذى حتى يراق على جوانبه الدم", author: "المتنبي", category: "كرامة" },
{ id: 14, quote: "عيد بأية حال عدت يا عيد بما مضى أم بأمر فيك تجديد", author: "المتنبي", category: "تأمل" },
{ id: 15, quote: "وما الخيل إلا كالصديق قليلة وإن كثرت في عين من لا يجرب", author: "المتنبي", category: "صداقة" },
{ id: 16, quote: "ذو العقل يشقى في النعيم بعقله وأخو الجهالة في الشقاوة ينعم", author: "المتنبي", category: "عقل" },
{ id: 17, quote: "وكم من عائب قولًا صحيحًا وآفته من الفهم السقيم", author: "المتنبي", category: "فكر" },
{ id: 18, quote: "ولكن تأخذ الآذان منه على قدر القرائح والعلوم", author: "المتنبي", category: "علم" },
{ id: 19, quote: "وإذا كانت النفوس كبارًا تعبت في مرادها الأجسام", author: "المتنبي", category: "طموح" },
{ id: 20, quote: "لا بقومي شرفت بل شرفوا بي وبنفسي فخرت لا بجدودي", author: "المتنبي", category: "اعتزاز" },
{ id: 21, quote: "ما كل ما يتمنى المرء يدركه وتجري الرياح بما لا تشتهي السفن", author: "المتنبي", category: "حكمة" },
{ id: 22, quote: "ومن طلب العلا من غير كد أضاع العمر في طلب المحال", author: "المتنبي", category: "اجتهاد" },
{ id: 23, quote: "وإذا أتتك مذمتي من ناقص فهي الشهادة لي بأني كامل", author: "المتنبي", category: "ثقة" },
{ id: 24, quote: "الرأي قبل شجاعة الشجعان", author: "المتنبي", category: "عقل" },
{ id: 25, quote: "هو أول وهي المحل الثاني", author: "المتنبي", category: "حكمة" },
{ id: 26, quote: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare", category: "Life" },
{ id: 27, quote: "The fault, dear Brutus, is not in our stars, but in ourselves.", author: "William Shakespeare", category: "Responsibility" },
{ id: 28, quote: "What cannot be eschewed must be embraced.", author: "William Shakespeare", category: "Wisdom" },
{ id: 29, quote: "Time's glory is to calm contending kings, to unmask falsehood, and bring truth to light.", author: "William Shakespeare", category: "Truth" },
{ id: 30, quote: "Beauty itself doth of itself persuade.", author: "William Shakespeare", category: "Beauty" },
{ id: 31, quote: "The better part of valor is discretion.", author: "William Shakespeare", category: "Wisdom" },
{ id: 32, quote: "We know what we are, but know not what we may be.", author: "William Shakespeare", category: "Life" },
{ id: 33, quote: "Brevity is the soul of wit.", author: "William Shakespeare", category: "Wisdom" },
{ id: 34, quote: "The empty vessel makes the loudest sound.", author: "William Shakespeare", category: "Wisdom" },
{ id: 35, quote: "Give every man thy ear, but few thy voice.", author: "William Shakespeare", category: "Wisdom" },
{ id: 36, quote: "To thine own self be true.", author: "William Shakespeare", category: "Character" },
{ id: 37, quote: "The course of true love never did run smooth.", author: "William Shakespeare", category: "Life" },
{ id: 38, quote: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", category: "Thought" },
{ id: 39, quote: "Some rise by sin, and some by virtue fall.", author: "William Shakespeare", category: "Morality" },
{ id: 40, quote: "No legacy is so rich as honesty.", author: "William Shakespeare", category: "Honesty" },
{ id: 41, quote: "Always do right. This will gratify some people, and astonish the rest.", author: "Mark Twain", category: "Morality" },
{ id: 42, quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", category: "Truth" },
{ id: 43, quote: "Truth is the most valuable thing we have. Let us economize it.", author: "Mark Twain", category: "Truth" },
{ id: 44, quote: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Success" },
{ id: 45, quote: "The best way to cheer yourself is to try to cheer somebody else up.", author: "Mark Twain", category: "Kindness" },
{ id: 46, quote: "Wrinkles should merely indicate where smiles have been.", author: "Mark Twain", category: "Happiness" },
{ id: 47, quote: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "Courage" },
{ id: 48, quote: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", category: "Kindness" },
{ id: 49, quote: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain", category: "Life" },
{ id: 50, quote: "Part of the secret of a success in life is to eat what you like and let the food fight it out inside.", author: "Mark Twain", category: "Life" },
{ id: 51, quote: "I have never let my schooling interfere with my education.", author: "Mark Twain", category: "Education" },
{ id: 52, quote: "Education consists mainly of what we have unlearned.", author: "Mark Twain", category: "Education" },
{ id: 53, quote: "The human race has one really effective weapon, and that is laughter.", author: "Mark Twain", category: "Humor" },
{ id: 54, quote: "It is better to take what is not yours than to leave it there, neglected.", author: "Mark Twain", category: "Wisdom" },
{ id: 55, quote: "Familiarity breeds contempt — and children.", author: "Mark Twain", category: "Humor" },
{ id: 56, quote: "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.", author: "Albert Einstein", category: "Education" },
{ id: 57, quote: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "Learning" },
{ id: 58, quote: "Curiosity is more important than intelligence.", author: "Albert Einstein", category: "Learning" },
{ id: 59, quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein", category: "Intelligence" },
{ id: 60, quote: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", category: "Education" },
{ id: 61, quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", category: "Thinking" },
{ id: 62, quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Learning" },
{ id: 63, quote: "The value of achievement lies in the achieving.", author: "Albert Einstein", category: "Success" },
{ id: 64, quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein", category: "Humanity" },
{ id: 65, quote: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein", category: "Peace" },
{ id: 66, quote: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "Success" },
{ id: 67, quote: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein", category: "Imagination" },
{ id: 68, quote: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "Intelligence" },
{ id: 69, quote: "Once you stop learning, you start dying.", author: "Albert Einstein", category: "Learning" },
{ id: 70, quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", category: "Life" },
{ id: 71, quote: "Sometimes it falls upon a generation to be great. You can be that great generation.", author: "Nelson Mandela", category: "Motivation" },
{ id: 72, quote: "While poverty persists, there is no true freedom.", author: "Nelson Mandela", category: "Freedom" },
{ id: 73, quote: "There are few misfortunes in the world that you cannot turn into a personal triumph if you have an iron will and the necessary skill.", author: "Nelson Mandela", category: "Resilience" },
{ id: 74, quote: "The brave man is not he who does not feel afraid, but he who conquers that fear.", author: "Nelson Mandela", category: "Courage" },
{ id: 75, quote: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", category: "Courage" },
{ id: 76, quote: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
{ id: 77, quote: "No one is born hating another person because of the color of his skin, or his background, or his religion.", author: "Nelson Mandela", category: "Humanity" },
{ id: 78, quote: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela", category: "Character" },
{ id: 79, quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Education" },
{ id: 80, quote: "It is in your hands to create a better world for all who live in it.", author: "Nelson Mandela", category: "Humanity" },
{ id: 81, quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Resilience" },
{ id: 82, quote: "After climbing a great hill, one only finds that there are many more hills to climb.", author: "Nelson Mandela", category: "Perseverance" },
{ id: 83, quote: "May your choices reflect your hopes, not your fears.", author: "Nelson Mandela", category: "Hope" },
{ id: 84, quote: "We must use time wisely and forever realize that the time is always ripe to do right.", author: "Nelson Mandela", category: "Wisdom" },
{ id: 85, quote: "It is said that no one truly knows a nation until one has been inside its jails.", author: "Nelson Mandela", category: "Reflection" },
{ id: 86, quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch", category: "Education" },
{ id: 87, quote: "The real problem is not whether machines think but whether men do.", author: "B. F. Skinner", category: "Thinking" },
{ id: 88, quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom" },
{ id: 89, quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", category: "Thinking" },
{ id: 90, quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "Excellence" },
{ id: 91, quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", category: "Education" },
{ id: 92, quote: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
{ id: 93, quote: "The beginning is the most important part of the work.", author: "Plato", category: "Success" },
{ id: 94, quote: "Knowledge is the food of the soul.", author: "Plato", category: "Knowledge" },
{ id: 95, quote: "Courage is knowing what not to fear.", author: "Plato", category: "Courage" },
{ id: 96, quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom" },
{ id: 97, quote: "An unexamined life is not worth living.", author: "Socrates", category: "Reflection" },
{ id: 98, quote: "I cannot teach anybody anything. I can only make them think.", author: "Socrates", category: "Education" },
{ id: 99, quote: "Wonder is the beginning of wisdom.", author: "Socrates", category: "Learning" },
{ id: 100, quote: "Know thyself.", author: "Socrates", category: "Wisdom" }
];

const b2 = [
{ id: 101, quote: "إذا أنت أكرمت الكريم ملكته وإن أنت أكرمت اللئيم تمردا", author: "المتنبي", category: "أخلاق" },
{ id: 102, quote: "ومن يجعل الضرغام بازًا لصيده تصيده الضرغام فيما تصيدا", author: "المتنبي", category: "حكمة" },
{ id: 103, quote: "لا خيل عندك تهديها ولا مال فليسعد النطق إن لم تسعد الحال", author: "المتنبي", category: "أدب" },
{ id: 104, quote: "وما قتل الأحرار كالعفو عنهم ومن لك بالحر الذي يحفظ اليدا", author: "المتنبي", category: "عفو" },
{ id: 105, quote: "ومن نكد الدنيا على الحر أن يرى عدوا له ما من صداقته بد", author: "المتنبي", category: "حكمة" },
{ id: 106, quote: "أعز مكان في الدنى سرج سابح وخير جليس في الزمان كتاب", author: "المتنبي", category: "قراءة" },
{ id: 107, quote: "وخير جليس في الزمان كتاب", author: "المتنبي", category: "قراءة" },
{ id: 108, quote: "مصائب قوم عند قوم فوائد", author: "المتنبي", category: "حكمة" },
{ id: 109, quote: "ومن طلب العلا سهر الليالي", author: "مثل عربي شائع", category: "اجتهاد" },
{ id: 110, quote: "إذا أنت لم تشرب مرارًا على القذى ظمئت وأي الناس تصفو مشاربه", author: "المتنبي", category: "صبر" },
{ id: 111, quote: "ومن يطلب العلا من غير كد أضاع العمر في طلب المحال", author: "مثل عربي", category: "اجتهاد" },
{ id: 112, quote: "إذا غامرت في أمر مروم فلا تقنع بما دون النجوم", author: "المتنبي", category: "طموح" },
{ id: 113, quote: "على قدر العزم تأتي العزائم", author: "المتنبي", category: "عزيمة" },
{ id: 114, quote: "وتعظم في عين الصغير صغارها وتصغر في عين العظيم العظائم", author: "المتنبي", category: "طموح" },
{ id: 115, quote: "ومن يطلب العلا من غير كد أضاع العمر في طلب المحال", author: "المتنبي", category: "اجتهاد" },
{ id: 116, quote: "إذا الشعب يومًا أراد الحياة فلا بد أن يستجيب القدر", author: "أبو القاسم الشابي", category: "إرادة" },
{ id: 117, quote: "ولا بد لليل أن ينجلي ولا بد للقيد أن ينكسر", author: "أبو القاسم الشابي", category: "أمل" },
{ id: 118, quote: "ومن لا يحب صعود الجبال يعش أبد الدهر بين الحفر", author: "أبو القاسم الشابي", category: "طموح" },
{ id: 119, quote: "إذا ما طمحت إلى غاية ركبت المنى ونسيت الحذر", author: "أبو القاسم الشابي", category: "طموح" },
{ id: 120, quote: "ومن يتهيب صعود الجبال يعش أبد الدهر بين الحفر", author: "أبو القاسم الشابي", category: "شجاعة" },
{ id: 121, quote: "وما نيل المطالب بالتمني ولكن تؤخذ الدنيا غلابا", author: "أحمد شوقي", category: "اجتهاد" },
{ id: 122, quote: "وما استعصى على قوم منال إذا الإقدام كان لهم ركابا", author: "أحمد شوقي", category: "عزيمة" },
{ id: 123, quote: "إنما الأمم الأخلاق ما بقيت فإن هم ذهبت أخلاقهم ذهبوا", author: "أحمد شوقي", category: "أخلاق" },
{ id: 124, quote: "صلاح أمرك للأخلاق مرجعه فقوم النفس بالأخلاق تستقم", author: "أحمد شوقي", category: "أخلاق" },
{ id: 125, quote: "وإذا أصيب القوم في أخلاقهم فأقم عليهم مأتمًا وعويلًا", author: "أحمد شوقي", category: "أخلاق" },
{ id: 126, quote: "قم للمعلم وفه التبجيلا كاد المعلم أن يكون رسولا", author: "أحمد شوقي", category: "تعليم" },
{ id: 127, quote: "أعلمت أشرف أو أجل من الذي يبني وينشئ أنفسًا وعقولًا", author: "أحمد شوقي", category: "تعليم" },
{ id: 128, quote: "وإنما الأمم الأخلاق ما بقيت فإن هم ذهبت أخلاقهم ذهبوا", author: "أحمد شوقي", category: "أخلاق" },
{ id: 129, quote: "بالعلم والمال يبني الناس ملكهم لم يبن ملك على جهل وإقلال", author: "أحمد شوقي", category: "علم" },
{ id: 130, quote: "ليس اليتيم من انتهى أبواه من هم الحياة وخلفاه ذليلًا", author: "أحمد شوقي", category: "حكمة" },
{ id: 131, quote: "إن اليتيم هو الذي تلقى له أمًا تخلت أو أبًا مشغولًا", author: "أحمد شوقي", category: "إنسانية" },
{ id: 132, quote: "العلم يرفع بيوتًا لا عماد لها والجهل يهدم بيت العز والكرم", author: "علي بن أبي طالب", category: "علم" },
{ id: 133, quote: "قيمة كل امرئ ما يحسنه", author: "علي بن أبي طالب", category: "قيمة" },
{ id: 134, quote: "المرء مخبوء تحت لسانه", author: "علي بن أبي طالب", category: "كلام" },
{ id: 135, quote: "لا تستوحشوا في طريق الهدى لقلة أهله", author: "علي بن أبي طالب", category: "ثبات" },
{ id: 136, quote: "من نصب نفسه للناس إمامًا فعليه أن يبدأ بتعليم نفسه قبل تعليم غيره", author: "علي بن أبي طالب", category: "تعليم" },
{ id: 137, quote: "العلم خير من المال؛ العلم يحرسك وأنت تحرس المال", author: "علي بن أبي طالب", category: "علم" },
{ id: 138, quote: "رب كلمة سلبت نعمة وجلبت نقمة", author: "علي بن أبي طالب", category: "كلام" },
{ id: 139, quote: "الناس أعداء ما جهلوا", author: "علي بن أبي طالب", category: "معرفة" },
{ id: 140, quote: "من كثر كلامه كثر خطؤه", author: "علي بن أبي طالب", category: "حكمة" },
{ id: 141, quote: "من علمني حرفًا فقد صيرني عبدًا", author: "علي بن أبي طالب", category: "تعليم" },
{ id: 142, quote: "العلم علمان: علم الأديان وعلم الأبدان", author: "علي بن أبي طالب", category: "علم" },
{ id: 143, quote: "العلم أكثر من أن يحاط به، فخذوا من كل شيء أحسنه", author: "علي بن أبي طالب", category: "تعلم" },
{ id: 144, quote: "لا خير في الصمت عن الحكم، كما أنه لا خير في القول بالجهل", author: "علي بن أبي طالب", category: "حكمة" },
{ id: 145, quote: "من قصر عن السياسة صغر عن الرياسة", author: "علي بن أبي طالب", category: "قيادة" },
{ id: 146, quote: "العلم في الصغر كالنقش على الحجر", author: "مثل عربي", category: "تعليم" },
{ id: 147, quote: "اطلبوا العلم ولو في الصين", author: "قول شائع", category: "تعلم" },
{ id: 148, quote: "من جد وجد، ومن زرع حصد", author: "مثل عربي", category: "اجتهاد" },
{ id: 149, quote: "لكل مجتهد نصيب", author: "مثل عربي", category: "اجتهاد" },
{ id: 150, quote: "من سار على الدرب وصل", author: "مثل عربي", category: "مثابرة" },
{ id: 151, quote: "خير الكلام ما قل ودل", author: "مثل عربي", category: "حكمة" },
{ id: 152, quote: "الوقت كالسيف إن لم تقطعه قطعك", author: "مثل عربي شائع", category: "وقت" },
{ id: 153, quote: "درهم وقاية خير من قنطار علاج", author: "مثل عربي", category: "حكمة" },
{ id: 154, quote: "العجلة من الشيطان", author: "مثل عربي", category: "تأنٍ" },
{ id: 155, quote: "في التأني السلامة وفي العجلة الندامة", author: "مثل عربي", category: "حكمة" },
{ id: 156, quote: "رب أخ لك لم تلده أمك", author: "مثل عربي", category: "صداقة" },
{ id: 157, quote: "الصديق وقت الضيق", author: "مثل عربي", category: "صداقة" },
{ id: 158, quote: "المرء على دين خليله", author: "حديث نبوي", category: "صحبة" },
{ id: 159, quote: "خيركم من تعلم القرآن وعلمه", author: "حديث نبوي", category: "تعليم" },
{ id: 160, quote: "من لا يَرحم لا يُرحم", author: "حديث نبوي", category: "رحمة" },
{ id: 161, quote: "إنما الأعمال بالنيات", author: "حديث نبوي", category: "نية" },
{ id: 162, quote: "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه", author: "حديث نبوي", category: "أخلاق" },
{ id: 163, quote: "الكلمة الطيبة صدقة", author: "حديث نبوي", category: "أخلاق" },
{ id: 164, quote: "من كان يؤمن بالله واليوم الآخر فليقل خيرًا أو ليصمت", author: "حديث نبوي", category: "كلام" },
{ id: 165, quote: "المؤمن للمؤمن كالبنيان يشد بعضه بعضًا", author: "حديث نبوي", category: "تعاون" },
{ id: 166, quote: "خير الناس أنفعهم للناس", author: "حديث مروي", category: "إنسانية" },
{ id: 167, quote: "يسروا ولا تعسروا، وبشروا ولا تنفروا", author: "حديث نبوي", category: "تعامل" },
{ id: 168, quote: "إن الله يحب إذا عمل أحدكم عملًا أن يتقنه", author: "قول مروي", category: "إتقان" },
{ id: 169, quote: "اغتنم خمسًا قبل خمس", author: "حديث نبوي", category: "وقت" },
{ id: 170, quote: "لا ضرر ولا ضرار", author: "حديث نبوي", category: "أخلاق" },
{ id: 171, quote: "اقرأ باسم ربك الذي خلق", author: "القرآن الكريم", category: "علم" },
{ id: 172, quote: "وقل رب زدني علمًا", author: "القرآن الكريم", category: "علم" },
{ id: 173, quote: "هل يستوي الذين يعلمون والذين لا يعلمون", author: "القرآن الكريم", category: "علم" },
{ id: 174, quote: "يرفع الله الذين آمنوا منكم والذين أوتوا العلم درجات", author: "القرآن الكريم", category: "علم" },
{ id: 175, quote: "فاسألوا أهل الذكر إن كنتم لا تعلمون", author: "القرآن الكريم", category: "تعلم" },
{ id: 176, quote: "إن الله لا يغير ما بقوم حتى يغيروا ما بأنفسهم", author: "القرآن الكريم", category: "تغيير" },
{ id: 177, quote: "وأن ليس للإنسان إلا ما سعى", author: "القرآن الكريم", category: "اجتهاد" },
{ id: 178, quote: "فإن مع العسر يسرًا، إن مع العسر يسرًا", author: "القرآن الكريم", category: "أمل" },
{ id: 179, quote: "ولا تيأسوا من روح الله", author: "القرآن الكريم", category: "أمل" },
{ id: 180, quote: "إن أكرمكم عند الله أتقاكم", author: "القرآن الكريم", category: "أخلاق" },
{ id: 181, quote: "وقل اعملوا فسيرى الله عملكم ورسوله والمؤمنون", author: "القرآن الكريم", category: "عمل" },
{ id: 182, quote: "وتعاونوا على البر والتقوى", author: "القرآن الكريم", category: "تعاون" },
{ id: 183, quote: "ولا تنسوا الفضل بينكم", author: "القرآن الكريم", category: "أخلاق" },
{ id: 184, quote: "إن الله يأمر بالعدل والإحسان", author: "القرآن الكريم", category: "عدل" },
{ id: 185, quote: "ادفع بالتي هي أحسن", author: "القرآن الكريم", category: "أخلاق" },
{ id: 186, quote: "وما توفيقي إلا بالله", author: "القرآن الكريم", category: "توكل" },
{ id: 187, quote: "ومن يتوكل على الله فهو حسبه", author: "القرآن الكريم", category: "توكل" },
{ id: 188, quote: "إن الله مع الصابرين", author: "القرآن الكريم", category: "صبر" },
{ id: 189, quote: "واصبر وما صبرك إلا بالله", author: "القرآن الكريم", category: "صبر" },
{ id: 190, quote: "فاذكروني أذكركم واشكروا لي ولا تكفرون", author: "القرآن الكريم", category: "شكر" },
{ id: 191, quote: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "Learning" },
{ id: 192, quote: "I have no special talent. I am only passionately curious.", author: "Albert Einstein", category: "Curiosity" },
{ id: 193, quote: "The only source of knowledge is experience.", author: "Albert Einstein", category: "Knowledge" },
{ id: 194, quote: "Imagination is more important than knowledge.", author: "Albert Einstein", category: "Imagination" },
{ id: 195, quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Learning" },
{ id: 196, quote: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Success" },
{ id: 197, quote: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain", category: "Thinking" },
{ id: 198, quote: "Continuous improvement is better than delayed perfection.", author: "Mark Twain", category: "Improvement" },
{ id: 199, quote: "The difference between the almost right word and the right word is really a large matter.", author: "Mark Twain", category: "Language" },
{ id: 200, quote: "Good breeding consists in concealing how much we think of ourselves, and how little we think of the other person.", author: "Mark Twain", category: "Character" }
];

const b3 = [
{ id: 201, quote: "المعرفة كالماء والهواء: هي حق لكل مواطن أن تتمتع بها مجانًا.", author: "طه حسين", category: "تعليم" },
{ id: 202, quote: "لا أحب الأوهام؛ وأنا مقتنع بأن الله وحده هو الذي يستطيع أن يخلق شيئًا من لا شيء.", author: "طه حسين", category: "فكر" },
{ id: 203, quote: "إن مصر الجديدة لن تنشأ إلا من مصر القديمة الخالدة.", author: "طه حسين", category: "وطن" },
{ id: 204, quote: "مستقبل الثقافة في مصر سيكون امتدادًا لماضيها العظيم.", author: "طه حسين", category: "ثقافة" },
{ id: 205, quote: "التعليم ليس امتيازًا لفئة، بل حق للجميع.", author: "طه حسين", category: "تعليم" },
{ id: 206, quote: "الكتاب صامت ما دمت تريد الصمت، بليغ حين تريد الحديث.", author: "الجاحظ", category: "قراءة" },
{ id: 207, quote: "الرجل الشريف لا يحتاج إلى أن يتظاهر بالفضيلة.", author: "الجاحظ", category: "أخلاق" },
{ id: 208, quote: "حين يبالغ الإنسان في صفاته، فذلك دليل على نقص فيها.", author: "الجاحظ", category: "شخصية" },
{ id: 209, quote: "التواضع خير من العفو، والعفو من أفضل أعمال الخير.", author: "الجاحظ", category: "أخلاق" },
{ id: 210, quote: "الكتاب أنيس لا يمل، وصاحب لا يخون.", author: "الجاحظ", category: "قراءة" },
{ id: 211, quote: "العلم يفتح للإنسان أبوابًا لا تفتحها القوة.", author: "الجاحظ", category: "علم" },
{ id: 212, quote: "الإنسان يعرف بفعله لا بما يدعيه لنفسه.", author: "الجاحظ", category: "أخلاق" },
{ id: 213, quote: "البلاغة ليست في كثرة الكلام، وإنما في إصابة المعنى.", author: "الجاحظ", category: "لغة" },
{ id: 214, quote: "لكل مقام مقال.", author: "الجاحظ", category: "بلاغة" },
{ id: 215, quote: "ليس كل ما يُعرف يُقال، ولا كل ما يُقال حضر وقته.", author: "الجاحظ", category: "حكمة" },
{ id: 216, quote: "إن الإنسان لا يستطيع أن يعيش بلا أمل.", author: "جبران خليل جبران", category: "أمل" },
{ id: 217, quote: "إن الحياة لا تعطي إلا من يعطيها.", author: "جبران خليل جبران", category: "حياة" },
{ id: 218, quote: "إنما الحياة مزيج من النور والظلام.", author: "جبران خليل جبران", category: "حياة" },
{ id: 219, quote: "إن المحبة لا تعطي إلا نفسها، ولا تأخذ إلا من نفسها.", author: "جبران خليل جبران", category: "محبة" },
{ id: 220, quote: "المحبة لا تملك شيئًا ولا تريد أن يملكها أحد.", author: "جبران خليل جبران", category: "محبة" },
{ id: 221, quote: "إن المحبة تكفي المحبة.", author: "جبران خليل جبران", category: "محبة" },
{ id: 222, quote: "إن أولادكم ليسوا أولادًا لكم.", author: "جبران خليل جبران", category: "تربية" },
{ id: 223, quote: "إنكم تستطيعون أن تمنحوهم محبتكم، ولكنكم لا تستطيعون أن تمنحوهم أفكاركم.", author: "جبران خليل جبران", category: "تربية" },
{ id: 224, quote: "لأن لهم أفكارهم الخاصة بهم.", author: "جبران خليل جبران", category: "تربية" },
{ id: 225, quote: "إن أجسادهم تسكن بيوتكم، ولكن نفوسهم تسكن في بيت الغد.", author: "جبران خليل جبران", category: "تربية" },
{ id: 226, quote: "أنتم الأقواس التي يقذف منها أولادكم أحياءً سهامًا إلى الأمام.", author: "جبران خليل جبران", category: "تربية" },
{ id: 227, quote: "إنكم تستطيعون أن تجتهدوا لتكونوا مثلهم، ولكنكم لا تستطيعون أن تجعلوهم مثلكم.", author: "جبران خليل جبران", category: "تربية" },
{ id: 228, quote: "إن الأرض تفرح أن تلامس أقدامكم العارية، والرياح تتوق إلى أن تلاعب شعوركم.", author: "جبران خليل جبران", category: "طبيعة" },
{ id: 229, quote: "إنكم تعطون القليل حين تعطون مما تملكون، ولكنكم تعطون حقًا حين تعطون من أنفسكم.", author: "جبران خليل جبران", category: "عطاء" },
{ id: 230, quote: "العطاء الذي لا يصحبه حب لا قيمة له.", author: "جبران خليل جبران", category: "عطاء" },
{ id: 231, quote: "إن العمل هو الحب الظاهر.", author: "جبران خليل جبران", category: "عمل" },
{ id: 232, quote: "إذا عجزتم عن العمل بمحبة، فالأفضل أن تتركوا العمل.", author: "جبران خليل جبران", category: "عمل" },
{ id: 233, quote: "إنكم تعملون لكي تسايروا الأرض وروحها.", author: "جبران خليل جبران", category: "عمل" },
{ id: 234, quote: "إن الحياة لا تسير إلى الوراء ولا تتوقف عند الأمس.", author: "جبران خليل جبران", category: "حياة" },
{ id: 235, quote: "إذا كانت الحياة قد أعطتك، فخذ منها بفرح، وإذا أخذت منك، فأعطها بفرح.", author: "جبران خليل جبران", category: "حياة" },
{ id: 236, quote: "One can never consent to creep when one feels an impulse to soar.", author: "Helen Keller", category: "طموح" },
{ id: 237, quote: "The world is full of suffering, but it is also full of the overcoming of it.", author: "Helen Keller", category: "أمل" },
{ id: 238, quote: "Optimism is the faith that leads to achievement.", author: "Helen Keller", category: "نجاح" },
{ id: 239, quote: "Life is either a daring adventure or nothing.", author: "Helen Keller", category: "حياة" },
{ id: 240, quote: "Knowledge is love and light and vision.", author: "Helen Keller", category: "علم" },
{ id: 241, quote: "Alone we can do so little; together we can do so much.", author: "Helen Keller", category: "تعاون" },
{ id: 242, quote: "The highest result of education is tolerance.", author: "Helen Keller", category: "تعليم" },
{ id: 243, quote: "Character cannot be developed in ease and quiet.", author: "Helen Keller", category: "شخصية" },
{ id: 244, quote: "What I am looking for is not out there, it is in me.", author: "Helen Keller", category: "تأمل" },
{ id: 245, quote: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller", category: "أمل" },
{ id: 246, quote: "Optimism is the faith that leads to achievement; nothing can be done without hope.", author: "Helen Keller", category: "أمل" },
{ id: 247, quote: "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.", author: "Helen Keller", category: "إنسانية" },
{ id: 248, quote: "Security is mostly a superstition.", author: "Helen Keller", category: "حياة" },
{ id: 249, quote: "Self-pity is our worst enemy.", author: "Helen Keller", category: "قوة" },
{ id: 250, quote: "What I am looking for is not out there, it is in me.", author: "Helen Keller", category: "تأمل" },
{ id: 251, quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", category: "أمل" },
{ id: 252, quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", category: "حياة" },
{ id: 253, quote: "A thing is not necessarily true because a man dies for it.", author: "Oscar Wilde", category: "تفكير" },
{ id: 254, quote: "Illusion is the first of all pleasures.", author: "Oscar Wilde", category: "فكر" },
{ id: 255, quote: "The truth is rarely pure and never simple.", author: "Oscar Wilde", category: "حقيقة" },
{ id: 256, quote: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde", category: "تعلم" },
{ id: 257, quote: "The smallest act of kindness is worth more than the grandest intention.", author: "Oscar Wilde", category: "لطف" },
{ id: 258, quote: "The one duty we owe to history is to rewrite it.", author: "Oscar Wilde", category: "تاريخ" },
{ id: 259, quote: "Life is far too important a thing ever to talk seriously about.", author: "Oscar Wilde", category: "حياة" },
{ id: 260, quote: "The only way to get rid of temptation is to yield to it.", author: "Oscar Wilde", category: "حكمة" },
{ id: 261, quote: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde", category: "تسامح" },
{ id: 262, quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde", category: "أمل" },
{ id: 263, quote: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde", category: "حياة" },
{ id: 264, quote: "The truth is rarely pure and never simple.", author: "Oscar Wilde", category: "حقيقة" },
{ id: 265, quote: "Anybody can make history. Only a great man can write it.", author: "Oscar Wilde", category: "تاريخ" },
{ id: 266, quote: "To improve is to change; to be perfect is to change often.", author: "Winston Churchill", category: "تطوير" },
{ id: 267, quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "مثابرة" },
{ id: 268, quote: "If you're going through hell, keep going.", author: "Winston Churchill", category: "مثابرة" },
{ id: 269, quote: "We shall never surrender.", author: "Winston Churchill", category: "ثبات" },
{ id: 270, quote: "The price of greatness is responsibility.", author: "Winston Churchill", category: "مسؤولية" },
{ id: 271, quote: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill", category: "تفكير" },
{ id: 272, quote: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", author: "Winston Churchill", category: "اجتهاد" },
{ id: 273, quote: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill", category: "عطاء" },
{ id: 274, quote: "Healthy citizens are the greatest asset any country can have.", author: "Winston Churchill", category: "مجتمع" },
{ id: 275, quote: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill", category: "تفاؤل" },
{ id: 276, quote: "The greatest lesson in life is to know that even fools are right sometimes.", author: "Winston Churchill", category: "حكمة" },
{ id: 277, quote: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: "Winston Churchill", category: "مبدأ" },
{ id: 278, quote: "We shape our buildings; thereafter they shape us.", author: "Winston Churchill", category: "مجتمع" },
{ id: 279, quote: "A lie gets halfway around the world before the truth has a chance to get its pants on.", author: "Winston Churchill", category: "حقيقة" },
{ id: 280, quote: "The empires of the future are the empires of the mind.", author: "Winston Churchill", category: "فكر" },
{ id: 281, quote: "The reward of a thing well done is having done it.", author: "Ralph Waldo Emerson", category: "إتقان" },
{ id: 282, quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "اختيار" },
{ id: 283, quote: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson", category: "طموح" },
{ id: 284, quote: "The creation of a thousand forests is in one acorn.", author: "Ralph Waldo Emerson", category: "أمل" },
{ id: 285, quote: "Every artist was first an amateur.", author: "Ralph Waldo Emerson", category: "تعلم" },
{ id: 286, quote: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson", category: "صبر" },
{ id: 287, quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson", category: "إنسانية" },
{ id: 288, quote: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson", category: "حكمة" },
{ id: 289, quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "قوة" },
{ id: 290, quote: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson", category: "صداقة" },
{ id: 291, quote: "The reward of a thing well done is having done it.", author: "Ralph Waldo Emerson", category: "إتقان" },
{ id: 292, quote: "Nothing external to you has any power over you.", author: "Ralph Waldo Emerson", category: "قوة" },
{ id: 293, quote: "Life consists in what a man is thinking of all day.", author: "Ralph Waldo Emerson", category: "تفكير" },
{ id: 294, quote: "Every sweet has its sour; every evil its good.", author: "Ralph Waldo Emerson", category: "حكمة" },
{ id: 295, quote: "The first wealth is health.", author: "Ralph Waldo Emerson", category: "حياة" },
{ id: 296, quote: "The desire of having is a very natural instinct.", author: "Ralph Waldo Emerson", category: "طبيعة" },
{ id: 297, quote: "People only see what they are prepared to see.", author: "Ralph Waldo Emerson", category: "إدراك" },
{ id: 298, quote: "Knowledge is when you learn something every day. Wisdom is when you let something go every day.", author: "Ralph Waldo Emerson", category: "حكمة" },
{ id: 299, quote: "The invariable mark of wisdom is to see the miraculous in the common.", author: "Ralph Waldo Emerson", category: "حكمة" },
{ id: 300, quote: "A great man is always willing to be little.", author: "Ralph Waldo Emerson", category: "تواضع" }
];

console.log("Batches 1, 2, 3 loaded:", b1.length, b2.length, b3.length);
