# Python script to build src/data/quotes.ts from all 10 batches provided by the user.

raw_text_batch_1 = """[
{ id: 1, quote: "على قدر أهل العزم تأتي العزائم", author: "المتنبي", category: "طموح" },
{ id: 2, quote: "وتأتي على قدر الكرام المكارم", author: "المتنبي", category: "أخلاق" },
{ id: 3, quote: "إذا غامرت في شرف مروم فلا تقنع بما دون النجوم", author: "المتنبي", category: "طموح" },
{ id: 4, quote: "فطعم الموت في أمر صغير كطعم الموت في أمر عظيم", author: "المتنبي", category: "شجاعة" },
{ id: 5, quote: "الرأي قبل شجاعة الشجعان هو أول وهي المحل الثاني", author: "المتنبي", category: "حكمة" },
{ id: 6, quote: "فإذا هما اجتمعا لنفس حرة بلغت من العلياء كل مكان", author: "المتنبي", category: "حكمة" },
{ id: 7, quote: "الخيل والليل والبيداء تعرفني والسيف والرمح والقرطاس والقلم", author: "المتنبي", category: "اعتزاز" },
{ id: 8, quote: "أنا الذي نظر الأعمى إلى أدبي وأسمعت كلماتي من به صمم", author: "المتنبي", category: "أدب" },
{ id: 9, quote: "إذا رأيت نيوب الليث بارزة فلا تظنن أن الليث يبتسم", author: "المتنبي", category: "حكمة" },
{ id: 10, quote: "ما كل ما يتمنى المرء يدركه", author: "المتنبي", category: "حكمة" },
{ id: 11, quote: "تجري الرياح بما لا تشتهي السفن", author: "المتنبي", category: "حكمة" },
{ id: 12, quote: "ومن يهن يسهل الهوان عليه ما لجرح بميت إيلام", author: "المتنبي", category: "كرامة" },
{ id: 13, quote: "لا يسلم الشرف الرفيع من الأذى حتى يراق على جوانبه الدم", author: "المتنبي", category: "كرامة" },
{ id: 14, quote: "عيد بأية حال عدت يا عيد بما مضى أم بأمر فيك تجديد", author: "المتنبي", category: "تأمل" },
{ id: 15, quote: "وما الخيل إلا كالصديق قليلة وإن كثرت في عين من لا يجرب", author: "المتنبي", category: "صداقة" },
{ id: 16, quote: "ذو العقل يشقى في النعيم بعقله وأخو الجهالة في الشقاوة ينعم", author: "المتنبي", category: "عقل" },
{ id: 17, quote: "وكم من عائب قولًا صحيحًا وآفته من الفهم السقيم", author: "المتنبي", category: "فكر" },
{ id: 18, quote: "ولكن تأخذ الآذان منه على قدر القرائح والعلوم", author: "المتنبي", category: "علم" },
{ id: 19, quote: "وإذا كانت النفوس كبارًا تعبت في مرادها الأجسام", author: "المتنبي", category: "طموح" },
{ id: 20, quote: "لا بقومي شرفت بل شرفوا بي وبنفسي فخرت لا بجدودي", author: "المتنبي", category: "اعتزاز" },
{ id: 21, quote: "ما كل ما يتمنى المرء يدركه وتجري الرياح بما لا تشتهي السفن", author: "المتنبي", category: "حكمة" },
{ id: 22, quote: "ومن طلب العلا من غير كد أضاع العمر في طلب المحال", author: "المتنبي", category: "اجتهاد" },
{ id: 23, quote: "وإذا أتتك مذمتي من ناقص فهي الشهادة لي بأني كامل", author: "المتنبي", category: "ثقة" },
{ id: 24, quote: "الرأي قبل شجاعة الشجعان", author: "المتنبي", category: "عقل" },
{ id: 25, quote: "هو أول وهي المحل الثاني", author: "المتنبي", category: "حكمة" },
{ id: 26, quote: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare", category: "Life" },
{ id: 27, quote: "The fault, dear Brutus, is not in our stars, but in ourselves.", author: "William Shakespeare", category: "Responsibility" },
{ id: 28, quote: "What cannot be eschewed must be embraced.", author: "William Shakespeare", category: "Wisdom" },
{ id: 29, quote: "Time's glory is to calm contending kings, to unmask falsehood, and bring truth to light.", author: "William Shakespeare", category: "Truth" },
{ id: 30, quote: "Beauty itself doth of itself persuade.", author: "William Shakespeare", category: "Beauty" },
{ id: 31, quote: "The better part of valor is discretion.", author: "William Shakespeare", category: "Wisdom" },
{ id: 32, quote: "We know what we are, but know not what we may be.", author: "William Shakespeare", category: "Life" },
{ id: 33, quote: "Brevity is the soul of wit.", author: "William Shakespeare", category: "Wisdom" },
{ id: 34, quote: "The empty vessel makes the loudest sound.", author: "William Shakespeare", category: "Wisdom" },
{ id: 35, quote: "Give every man thy ear, but few thy voice.", author: "William Shakespeare", category: "Wisdom" },
{ id: 36, quote: "To thine own self be true.", author: "William Shakespeare", category: "Character" },
{ id: 37, quote: "The course of true love never did run smooth.", author: "William Shakespeare", category: "Life" },
{ id: 38, quote: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare", category: "Thought" },
{ id: 39, quote: "Some rise by sin, and some by virtue fall.", author: "William Shakespeare", category: "Morality" },
{ id: 40, quote: "No legacy is so rich as honesty.", author: "William Shakespeare", category: "Honesty" },
{ id: 41, quote: "Always do right. This will gratify some people, and astonish the rest.", author: "Mark Twain", category: "Morality" },
{ id: 42, quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain", category: "Truth" },
{ id: 43, quote: "Truth is the most valuable thing we have. Let us economize it.", author: "Mark Twain", category: "Truth" },
{ id: 44, quote: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Success" },
{ id: 45, quote: "The best way to cheer yourself is to try to cheer somebody else up.", author: "Mark Twain", category: "Kindness" },
{ id: 46, quote: "Wrinkles should merely indicate where smiles have been.", author: "Mark Twain", category: "Happiness" },
{ id: 47, quote: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "Courage" },
{ id: 48, quote: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", category: "Kindness" },
{ id: 49, quote: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain", category: "Life" },
{ id: 50, quote: "Part of the secret of a success in life is to eat what you like and let the food fight it out inside.", author: "Mark Twain", category: "Life" },
{ id: 51, quote: "I have never let my schooling interfere with my education.", author: "Mark Twain", category: "Education" },
{ id: 52, quote: "Education consists mainly of what we have unlearned.", author: "Mark Twain", category: "Education" },
{ id: 53, quote: "The human race has one really effective weapon, and that is laughter.", author: "Mark Twain", category: "Humor" },
{ id: 54, quote: "It is better to take what is not yours than to leave it there, neglected.", author: "Mark Twain", category: "Wisdom" },
{ id: 55, quote: "Familiarity breeds contempt — and children.", author: "Mark Twain", category: "Humor" },
{ id: 56, quote: "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.", author: "Albert Einstein", category: "Education" },
{ id: 57, quote: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "Learning" },
{ id: 58, quote: "Curiosity is more important than intelligence.", author: "Albert Einstein", category: "Learning" },
{ id: 59, quote: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein", category: "Intelligence" },
{ id: 60, quote: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", category: "Education" },
{ id: 61, quote: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein", category: "Thinking" },
{ id: 62, quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Learning" },
{ id: 63, quote: "The value of achievement lies in the achieving.", author: "Albert Einstein", category: "Success" },
{ id: 64, quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein", category: "Humanity" },
{ id: 65, quote: "Peace cannot be kept by force; it can only be achieved by understanding.", author: "Albert Einstein", category: "Peace" },
{ id: 66, quote: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "Success" },
{ id: 67, quote: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein", category: "Imagination" },
{ id: 68, quote: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "Intelligence" },
{ id: 69, quote: "Once you stop learning, you start dying.", author: "Albert Einstein", category: "Learning" },
{ id: 70, quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", category: "Life" },
{ id: 71, quote: "Sometimes it falls upon a generation to be great. You can be that great generation.", author: "Nelson Mandela", category: "Motivation" },
{ id: 72, quote: "While poverty persists, there is no true freedom.", author: "Nelson Mandela", category: "Freedom" },
{ id: 73, quote: "There are few misfortunes in the world that you cannot turn into a personal triumph if you have an iron will and the necessary skill.", author: "Nelson Mandela", category: "Resilience" },
{ id: 74, quote: "The brave man is not he who does not feel afraid, but he who conquers that fear.", author: "Nelson Mandela", category: "Courage" },
{ id: 75, quote: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", category: "Courage" },
{ id: 76, quote: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation" },
{ id: 77, quote: "No one is born hating another person because of the color of his skin, or his background, or his religion.", author: "Nelson Mandela", category: "Humanity" },
{ id: 78, quote: "A good head and a good heart are always a formidable combination.", author: "Nelson Mandela", category: "Character" },
{ id: 79, quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Education" },
{ id: 80, quote: "It is in your hands to create a better world for all who live in it.", author: "Nelson Mandela", category: "Humanity" },
{ id: 81, quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Resilience" },
{ id: 82, quote: "After climbing a great hill, one only finds that there are many more hills to climb.", author: "Nelson Mandela", category: "Perseverance" },
{ id: 83, quote: "May your choices reflect your hopes, not your fears.", author: "Nelson Mandela", category: "Hope" },
{ id: 84, quote: "We must use time wisely and forever realize that the time is always ripe to do right.", author: "Nelson Mandela", category: "Wisdom" },
{ id: 85, quote: "It is said that no one truly knows a nation until one has been inside its jails.", author: "Nelson Mandela", category: "Reflection" },
{ id: 86, quote: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch", category: "Education" },
{ id: 87, quote: "The real problem is not whether machines think but whether men do.", author: "B. F. Skinner", category: "Thinking" },
{ id: 88, quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom" },
{ id: 89, quote: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", category: "Thinking" },
{ id: 90, quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "Excellence" },
{ id: 91, quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", category: "Education" },
{ id: 92, quote: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness" },
{ id: 93, quote: "The beginning is the most important part of the work.", author: "Plato", category: "Success" },
{ id: 94, quote: "Knowledge is the food of the soul.", author: "Plato", category: "Knowledge" },
{ id: 95, quote: "Courage is knowing what not to fear.", author: "Plato", category: "Courage" },
{ id: 96, quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom" },
{ id: 97, quote: "An unexamined life is not worth living.", author: "Socrates", category: "Reflection" },
{ id: 98, quote: "I cannot teach anybody anything. I can only make them think.", author: "Socrates", category: "Education" },
{ id: 99, quote: "Wonder is the beginning of wisdom.", author: "Socrates", category: "Learning" },
{ id: 100, quote: "Know thyself.", author: "Socrates", category: "Wisdom" }
]"""

print("Script template ready")
